name: "SCA"

on:
  workflow_dispatch:
  workflow_call:
    inputs:
      username:
        required: false
        type: string
    secrets:
      token:
        required: false
  schedule:
    - cron: '1 0 * * 6'

jobs:
  sca:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v4
      
      - name: Restore tools
        run: dotnet tool restore

      - name: Run SCA
        uses: tonycknight/pkgchk-action@v1.0.22
        with:
          deprecated: true
          vulnerable:  true
          transitives: true